### ISSUE TITLE
Show friendly error messages on login failure (Throttled login)

### ISSUE THREAD

**Issue by DotNetSimon** [FAForever/faf-user-service#6]
**Describe the bug**
When attempting failed login multiple times in a row, you get an error report instead of a nice client error

**To Reproduce**
Login with wrong password 3x quickly in a row

**Log or error message**
This is my log file:
```
java.lang.RuntimeException: Error during login
	at com.faforever.client.login.LoginController.lambda$initialize$13(LoginController.java:207)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyStringPropertyBase.fireValueChangedEvent(ReadOnlyStringPropertyBase.java:72)
	at javafx.beans.property.ReadOnlyStringWrapper.fireValueChangedEvent(ReadOnlyStringWrapper.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
	at javafx.scene.web.WebEngine.updateLocation(WebEngine.java:434)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1364)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1239)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2524)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2369)
	at com.sun.webkit.network.URLLoaderBase.twkWillSendRequest(Native Method)
	at com.sun.webkit.network.HTTP2Loader.lambda$willSendRequest$14(HTTP2Loader.java:497)
	at com.sun.webkit.network.HTTP2Loader.lambda$callBackIfNotCanceled$10(HTTP2Loader.java:437)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Expected behavior**
Show a user friendly error message saying something along the lines of "You have to wait a little before trying to login again."

**Screenshots**
![image](https://user-images.githubusercontent.com/86734095/125452144-e1cdd4a2-f56a-4a1e-a3db-b41b3691d638.png)

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Brutus5000** [comment]
Closed by #8
